server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true